name: 'API Governance Test'

on:
  push:
  workflow_dispatch:

jobs:
  schema:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: treblle/api-insights-action@v1
      with:
        schema: ./openapi.yml
